#!/bin/bash
#
# Assumptions:
#  - we are tracking cases on the 'cases' branch which already exists

source git-case-common

DESCRIPTION=$@
test -z "$DESCRIPTION" && die "$0 <description>"

CASE_NAME=$(date +%Y%m%d-%H%M%S.%N:)$(echo -n "$DESCRIPTION" | tr -c "a-zA-Z0-9" -)

# we work in the working dir
test -d "$GIT_CASE_WORK_DIR" && die "stale $GIT_CASE_WORK_DIR already exists"
mkdir -p "$GIT_CASE_WORK_DIR"
cd "$GIT_CASE_WORK_DIR"

# build the tree
mkdir -p "$CASE_NAME"
echo "$DESCRIPTION"                           > "$CASE_NAME/description"
git rev-parse HEAD                            > "$CASE_NAME/found"
echo new                                      > "$CASE_NAME/state"
echo v0.0                                     > "$CASE_NAME/version"

git read-tree --reset "$GIT_CASE_HEAD"

git update-index --add "$CASE_NAME/description"
git update-index --add "$CASE_NAME/found"
git update-index --add "$CASE_NAME/state"
git update-index --add "$CASE_NAME/version"

TREE=$(git write-tree)
test -z "$TREE" && die "failed to write tree"

COMMIT=$(echo "$DESCRIPTION" | git commit-tree ${TREE} -p cases)
test -z "$COMMIT" && die "failed to create commit"

echo "$COMMIT" > "${GIT_DIR}/refs/heads/$GIT_CASE_HEAD"

