#!/bin/bash
#
# Assumptions:
#  - in a git repository
#  - the branch defined by GIT_CASE_HEAD exists (see git-case-common)

source git-case-common

git ls-tree cases -- . | while read mode type object file ; do
        if test $type = tree ; then
                short=$(gen_short_case_id $file)
                desc=$(git show cases:$file/description | head -n1)
                state="["$(git show cases:$file/state)"]"
                printf "%6s   %7s  %s\n" "$short" "$state" "$desc"
        fi
done
