#!/bin/bash
#
# Assumptions:
#  - in a git repository
#  - we can access git-case-common
#  - the branch defined by GIT_CASE_HEAD exists (see git-case-common)

source git-case-common

ID=$(cat "$GIT_CASE_ACTIVE" 2>/dev/null || true)
test -z "$ID" && die "no active case set"
ASSIGNED_FILE="$ID/assigned"

case "${#@}" in
        0)      exec git show "cases:$ASSIGNED_FILE"
                ;;
        1)      WHO="$1"
                ;;
        2)      ID="$1"
                WHO="$2"
                ;;
        *)
                echo "Usage: $0 [caseid] user"
                exit -1
esac

if test "$WHO" = "--me" ; then
        WHO="$GIT_COMMITTER_NAME <$GIT_COMMITTER_EMAIL>"
fi

# we work in the working dir
go_to_git_case_work_dir

git read-tree -i --reset "$GIT_CASE_HEAD"

add_file_to_index "$ASSIGNED_FILE" "$WHO"

commit_index_and_update_branch "${ID:0:6} assigned to '$WHO'" "-p $GIT_CASE_HEAD"
