#!/bin/bash
#
# Assumptions:
#  - in a git repository
#  - we can access git-case-common
#  - the branch defined by GIT_CASE_HEAD exists (see git-case-common)

source git-case-common

ID=$1
if test -z "$ID" ; then
        active=$(cat "${GIT_CASE_ACTIVE}" 2>/dev/null || true)
        test -z "$active" && die "no case active"
        echo "Active case: $active"
        exit 0
fi

CNT=$(git ls-tree cases | awk " /\<${ID}[a-zA-Z0-9.-]*$/"'{ print $4 }' | wc -l)
test "$CNT" -gt 1 && die "ID is ambiguous, select a full ID"
test "$CNT" -lt 1 && die "ID does not match a case"

FULL_ID=$(git ls-tree cases | awk " /\<${ID}[a-zA-Z0-9-]*$/"'{ print $4 }')

echo "$FULL_ID" > "${GIT_CASE_ACTIVE}"
