#!/bin/bash
#
# Assumptions:
#  - in a git repository
#  - we can access git-case-common
#  - the branch defined by GIT_CASE_HEAD exists (see git-case-common)

source git-case-common

ID=$1
if test -z "$ID" ; then
        ID=$(cat "$GIT_CASE_ACTIVE" 2>/dev/null || true)
        test -z "$ID" && die "no active case set"
fi
ID=$(git ls-tree cases | awk "/\<${ID}[a-fA-F0-9]*$/"'{ print $4 }')
shortID=$(gen_short_case_id "$ID")

CASE_ROOT="cases:${ID}"

desc=$(git show "$CASE_ROOT/description" 2>/dev/null || true)
test -z "$desc" && die "active case is not valid"

cdate=$(git show "$CASE_ROOT/created" 2>/dev/null || true)
ctype=$(git show "$CASE_ROOT/type" 2>/dev/null || true)
state=$(git show "$CASE_ROOT/state" 2>/dev/null || true)
assig=$(git show "$CASE_ROOT/assigned" 2>/dev/null || true)
found=$(git show "$CASE_ROOT/found" 2>/dev/null || true)

found=$(git log -1 --pretty=oneline --abbrev-commit "$found" || echo "$found")

mine=""
if test "$assig" = "$GIT_COMMITTER_NAME <$GIT_COMMITTER_EMAIL>" \
                -o "$assig" = "$GIT_COMMITTER_EMAIL" ; then
        mine="$bold$blue"
elif test -z "$assig" ; then
        mine="$bold$black"
        assig="(nobody)"
fi

echo -e "Case ID:     $bold$blue$shortID$reset ($white$ID$reset)"
echo -e "Description: $yellow$desc$reset"
echo    "Created on:  $cdate"
echo    "Type:        $ctype"
echo    "State:       $state"
echo -e "Assigned to: $mine$assig$reset"
echo    "Found in:    $found"

MARKS=$(git ls-tree cases "$ID/marks/" | awk -F/ '{ print $3 }' | xargs)
test -n "$MARKS" && echo "Marks:       $MARKS"

FIELDS=$(git ls-tree cases "$ID/fields/" | awk -F/ '{ print $3 }' | xargs)
if test -n "$FIELDS" ; then
        echo
        echo "Fields..."
        git ls-tree cases -- "$ID/fields/" | while read mode type object file ; do
                if test $type = blob ; then
                        short=${file##*/}:
                        printf "  * %-10s" $short
                        git cat-file blob $object | sed 's/^/      /'
                fi
        done
fi

COMMENT_FILESS=$(git ls-tree cases -- "$ID/comments/")
test -z "$COMMENT_FILESS" && exit 0

echo
echo "Comments..."
git ls-tree cases -- "$ID/comments/" | while read mode type object file ; do
        if test $type = blob ; then
                short=${file##*/}
                echo "  * $short"
                git cat-file blob $object | sed 's/^/      /'
                echo
        fi
done
