#!/bin/bash
#
# Assumptions:
#  - in a git repository
#  - the branch defined by GIT_CASE_HEAD exists (see git-case-common)

source git-case-common

ACTIVE_ID=$(cat "$GIT_CASE_ACTIVE" 2>/dev/null || true)

git ls-tree cases -- . | while read mode type object file ; do
        if test $type = tree ; then
                short=$(gen_short_case_id $file)
                desc=$(git show cases:$file/description 2>/dev/null | head -n1)
                ctype=$(git show "cases:$file/type" 2>/dev/null || true)
                state=$(git show "cases:$file/state" 2>/dev/null || true)
                assig=$(git show "cases:$file/assigned" 2>/dev/null || true)

                mine=""
                if test "$assig" = "$GIT_COMMITTER_NAME <$GIT_COMMITTER_EMAIL>" \
                                -o "$assig" = "$GIT_COMMITTER_EMAIL" ; then
                        mine="$bold$blue"
                elif test -z "$assig" ; then
                        mine="$bold$black"
                fi

                cur="  "
                if test "$file" = "$ACTIVE_ID" ; then
                        cur="$bold$red**$reset"
                fi

                state_type="[$state] [$ctype]"
                printf "$cur $mine%6s$reset  %-20s $mine%s$reset\n" "$short" "$state_type" "${desc:0:50}"
        fi
done
